name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  crear_y_desplegar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar `pipelines` de Acquia
        run: |
          wget -O $HOME/pipelines https://cloud.acquia.com/pipeline-client/download
          chmod +x $HOME/pipelines

      - name: Configurar credenciales de Acquia
        run: |
          $HOME/pipelines configure --key=9f3f2960-a7fd-44e4-9b00-3aa3348e8fda --secret=Jv/S1pTRtQVXBVVjLYBpTd3FiWW2avBtcpzg5e5puyQ=

      - name: Iniciar el pipeline
        run: |
          $HOME/pipelines start --application-id=02506fe7-50cb-4c7d-8a8d-71829159435a

      - name: Monitorear el estado del pipeline
        run: |
          echo "Consultando el estado del pipeline..."
          while true; do
              ESTADO=$($HOME/pipelines status --application-id=02506fe7-50cb-4c7d-8a8d-71829159435a | grep Status)
              if [[ $ESTADO == *"Status: running"* || $ESTADO == *"Status: started"* ]]; then
                  echo "El pipeline $ESTADO -> Consultando nuevamente en 10 segundos..."
                  sleep 10
              elif [[ $ESTADO == *"Status: succeeded"* ]]; then
                  echo "El pipeline ha finalizado con éxito."
                  echo "Desplegando al ambiente ${{ github.event.inputs.ambiente }}"
                  acli api:environments:code-switch "unisabanastart.${{ github.event.inputs.ambiente }}" "pipelines-build-${{ github.ref_name }}"
                  break
              elif [[ $ESTADO == *"Status: failed"* ]]; then
                  echo "El pipeline ha fallado."
                  exit 1
              else
                  echo "Estado desconocido: $ESTADO"
                  echo "El pipeline ha finalizado con éxito."
                  echo "Desplegando al ambiente ${{ github.event.inputs.environment }}
                  acli api:environments:code-switch "unisabanastart.${{ github.event.inputs.environment }} "pipelines-build-${{ github.ref_name }}"
                  exit 1
              fi
          done

      - name: Verificar el despliegue
        run: |
          echo "Despliegue completado o fallido."
