name: Crear Tag y Desplegar

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  crear_y_desplegar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar `pipelines` CLI de Acquia
        run: |
          wget -O $HOME/pipelines https://cloud.acquia.com/pipeline-client/download
          chmod +x $HOME/pipelines

      - name: Configurar credenciales de Acquia
        run: |
          $HOME/pipelines configure --application-id="${{ secrets.ACQUIA_ID }}" --key="${{ secrets.ACQUIA_KEY }}" --secret="${{ secrets.ACQUIA_SECRET }}"

      - name: Iniciar el pipeline
        run: |
          echo "Iniciando el pipeline..."
          $HOME/pipelines start

      - name: Monitorear el estado del pipeline
        run: |
          echo "Consultando el estado del pipeline..."
          while true; do
              ESTADO=$($HOME/pipelines status | grep Status)
              if [[ $ESTADO == *"Status: running"* || $ESTADO == *"Status: started"* ]]; then
                  echo "El pipeline $ESTADO -> Consultando nuevamente en 10 segundos..."
                  sleep 10
              elif [[ $ESTADO == *"Status: succeeded"* ]]; then
                  echo "El pipeline ha finalizado con éxito."
                  echo "Desplegando al ambiente stage"
                  acli api:environments:code-switch unisabanastart.stage "pipelines-build-${{ github.ref_name }}"
                  break
              elif [[ $ESTADO == *"Status: failed"* ]]; then
                  echo "El pipeline ha fallado."
                  exit 1
              else
                  echo "Estado desconocido: $ESTADO"
                  exit 1
              fi
          done

      - name: Verificar el despliegue
        run: |
          echo "Despliegue completado o fallido."
